trainer:
  max_epochs: 100
  accumulate_grad_batches: 2
  num_sanity_val_steps: 2
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: aait_imrec
      log_model: false
  log_every_n_steps: 50
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: ./checkpoints
        auto_insert_metric_name: false
        filename: "epoch={epoch}_step={step}_acc_mean={classification/acc_mean:.4f}"
        save_last: true
        save_top_k: 20
        every_n_epochs: 5
        monitor: classification/acc_mean
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: classification_callback.ClassificationCallback
      init_args:
        datamodule:
          class_path: datamodules.Task1Datamodule
          init_args:
            path: /home/doved/Data/AAIT/task1
            batch_size: 64
            num_train_workers: 0
            num_val_workers: 0
            labeled: true
            unlabeled: false
            no_train_augmentations: true
        early_stopping: 10
        max_depth: 4
        n_estimators: 100
        pca_n_components: 256
        val_n_splits: 5
        val_n_repeats: 5
        xgb_device: cuda
        every_n_epochs: 5
        skip_sanity_check: false

model:
  class_path: models.ByolModel
  init_args:
    base_tau: 0.99
    mlp_hidden_size: 4096
    mlp_out_size: 256
    lr: 3e-4
    weight_decay: 1.5e-6
    warmup_epochs: 10
    backbone:
      class_path: models.TimmModel
      init_args:
        model_name: resnet50
        pretrained: true

data:
  class_path: datamodules.Task1Datamodule
  init_args:
    path: AAIT/task1
    batch_size: 512
    num_train_workers: 4
    num_val_workers: 4
    num_test_workers: 4
    labeled: true
    unlabeled: true
    val_size: 0
    byol: true
    train_dataset_replicas: 3
