# lightning.pytorch==2.1.2
seed_everything: 3576777919
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: null
      save_dir: .
      version: null
      offline: false
      dir: null
      id: null
      anonymous: null
      project: aait_imrec
      log_model: false
      experiment: null
      prefix: ''
      checkpoint_name: null
      job_type: null
      config: null
      entity: null
      reinit: null
      tags: null
      group: null
      notes: null
      magic: null
      config_exclude_keys: null
      config_include_keys: null
      mode: null
      allow_val_change: null
      resume: null
      force: null
      tensorboard: null
      sync_tensorboard: null
      monitor_gym: null
      save_code: null
      settings: null
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: ./checkpoints
      filename: epoch={epoch}_step={step}_val_0_loss={val_0/loss:.4f}
      monitor: val_0/loss
      verbose: false
      save_last: true
      save_top_k: 5
      save_weights_only: false
      mode: min
      auto_insert_metric_name: false
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: 1
      save_on_train_epoch_end: null
      enable_version_counter: true
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: step
      log_momentum: false
      log_weight_decay: false
  fast_dev_run: false
  max_epochs: 50
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 2
  log_every_n_steps: 20
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
ckpt_path: null
model:
  class_path: models.SupervisedModel
  init_args:
    backbone:
      class_path: models.TimmModel
      init_args:
        model_name: efficientnetv2_s
        pretrained: false
        model: null
        byol_ckpt_path: null
        timm_ckpt_path: /home/doved/Downloads/checkpoint-224.pth.tar
    unfreeze_backbone_at_epoch: 20
    warmup_epochs: 10
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0
data:
  class_path: datamodules.Task1Datamodule
  init_args:
    path: /home/doved/Data/AAIT/task1
    num_train_workers: 8
    num_val_workers: 8
    num_test_workers: 8
    batch_size: 1024
    labeled: true
    unlabeled: false
    val_size: 0.2
    no_train_augmentations: true
    byol: false
    dino: false
    train_dataset_replicas: 5
    resize_img_to: 64
    model_img_size: 56
