trainer:
  max_epochs: 50
  accumulate_grad_batches: 2
  num_sanity_val_steps: 2
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: aait_imrec
      log_model: false
  log_every_n_steps: 20
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: ./checkpoints
        auto_insert_metric_name: false
        filename: "epoch={epoch}_step={step}_val_0_loss={val_0/loss:.4f}"
        save_last: true
        save_top_k: 5
        every_n_epochs: 1
        monitor: val_0/loss
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step

model:
  class_path: models.SupervisedModel
  init_args:
    backbone:
      class_path: models.Ensemble
      init_args:
        learnable_weights: false
        models:
          - class_path: models.TimmModel
            init_args:
              model_name: efficientnetv2_s
              # finetuned_ckpt_path: efficientnetv2_s.final.ckpt
              timm_ckpt_path: efficientnetv2_s.pth.tar
              pretrained: false
              task_number: 2
#           - class_path: models.TimmModel
#             init_args:
#               model_name: resnet50
# #              finetuned_ckpt_path: resnet50.lr01.final.ckpt
#               timm_ckpt_path: resnet50.lr01.pth.tar
#               pretrained: false
#               task_number: 2
          # - class_path: models.TimmModel
          #   init_args:
          #     model_name: vit_large_patch16_224
          #     pretrained: true
          #     use_hq_images: true
          # - class_path: models.TimmModel
          #   init_args:
          #     model_name: vit_large_patch14_clip_224
          #     pretrained: true
          #     use_hq_images: true
          # - class_path: models.TimmModel
          #   init_args:
          #     model_name: efficientnetv2_rw_m
          #     pretrained: true
          #     use_hq_images: true
          # - class_path: models.TimmModel
          #   init_args:
          #     model_name: efficientnetv2_rw_s
          #     pretrained: true
          #     use_hq_images: true
          # - class_path: models.TimmModel
          #   init_args:
          #     model_name: ecaresnet269d
          #     pretrained: true
          #     use_hq_images: true
          # - class_path: models.TimmModel
          #   init_args:
          #     model_name: seresnet152d
          #     pretrained: true
          #     use_hq_images: true

# resnext101_64x4d - 77
# resnet152 - 77
# efficientnet_b4 - 78
# seresnet152d - 78
# seresnext101d_32x8d - 77
# vit_base_patch16_224 - 78

# ecaresnet269d - 79
# efficientnetv2_rw_s - 79
# efficientnetv2_rw_m - 79

# vit_large_patch16_224 - 83
# vit_large_patch14_clip_224 80

    # unfreeze_only_ensemble_weights: true
    unfreeze_backbone_at_epoch: 20
    warmup_epochs: 5
    lr: 0.001
    weight_decay: 0.0001

data:
  class_path: datamodules.Task1Datamodule
  init_args:
    path: /home/doved/Data/AAIT/task2
    hq_path: /home/doved/Data/AAIT_upsampled/task2
    load_hq_images: false
    batch_size: 1024
    num_train_workers: 8
    num_val_workers: 8
    num_test_workers: 8
    labeled: true
    unlabeled: false
    val_size: 0.2
    train_dataset_replicas: 5
    # no_train_augmentations: true
#    resize_img_to: 256
#    model_img_size: 224
    # resize_img_to: 64
    # model_img_size: 56
